# Generated by Django 4.0 on 2021-12-09 09:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
